apiVersion: v1
kind: ConfigMap
metadata:
  name: back-service-config
data:
  springAppName: back-service
---
apiVersion: apps/v1 # need to be 'apps/v1', only 'v1' will fail
kind: Deployment
metadata:
  name: back-service-deployment
  labels:
    app: back-service
spec:
  selector:
    matchLabels:
      app: back-service
  template:
    metadata:
      labels:
        app: back-service
    spec:
      containers:
      - name: back-service-container
        image: asia.gcr.io/aiot-vn-loancloud-dev/back-service:0.1.0
        ports:
        - containerPort: 8080
          name: http-web-svc
        envFrom:
        - configMapRef:
            name: back-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: back-service-svc
spec:
  type: LoadBalancer
  selector:
    app: back-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: http-web-svc
